### ISSUE TITLE
lodash-es causing issue in ts-node

### ISSUE THREAD

**Issue by develomark** [ridi/object-case-converter#7]
As node does not support es modules without the --experimental-modules this package is currently not suited to a node app, whilst it works perfectly with babel/webpack.

ts-node does not support --experimental-modules so therefore there is not a way to make this object-case-converter function without modification:

```
node_modules/lodash-es/lodash.js:10
export { default as add } from './add.js';
^^^^^^

SyntaxError: Unexpected token export
```

By modifying the lodash imports to:

```
import camelCase from 'lodash/camelCase';
import  snakeCase from 'lodash/snakeCase';
```
it should work perfectly with es5 and therefore ts-node.

Thoughts?

**Comment by J132134** [comment]
Thanks to your comment.
This issue resolved and published to v2.0.1.

Welcome your continuous feedback.
